name: CI

on:
  push:
    branches:
      - main
      - nsb2-interface
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  cpp:
    runs-on: ubuntu-22.04
    container: rootproject/root:6.32.02-ubuntu22.04
    steps:
      - name: Install build dependencies
        run: apt-get update && apt-get install -y cmake g++ git make zlib1g-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Build and test
        run: |
          cmake -S . -B build -DWITH_TEST=ON -DWITH_ROOT=ON
          cmake --build build -j 5
          cmake --install build --prefix install
          cd build && ctest --extra-verbose --output-on-failure
